version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Build documentation in the doc/ directory with Sphinx
sphinx:
  configuration: doc/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
formats:
  - pdf
  - epub

# Python environment required to build your docs
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev
