name: Tag Triggered Workflow

on:
  push:
    branches:
      - upload_to_pypi
#    tags:
#      - 'v*'

jobs:

  build-wheel:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[dev]

    - name: Create wheel
      run: python -m build --wheel --no-isolation

#    - name: Upload wheel
#      uses: actions/upload-artifact@v3
#      with:
#        name: wheel
#        path: dist/bumps-*-py3-none-any.whl

  test-wheel:
    runs-on: ubuntu-latest
    needs: build-wheel
    steps:

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest

#    - name: Download wheel
#      uses: actions/download-artifact@v3
#      with:
#        name: wheel
#        path: dist

    - name: Check contents
      run: |
        pwd
        ls -R ./

#    - name: Install wheel
#      run: python -m pip install ./dist/bumps-*-py3-none-any.whl

#    - name: Run tests
#      run: pytest -v --ignore=bumps/webview

#    - name: Check examples
#      run: python check_examples.py --chisq

#    - name: Check fitters
#      run: python check_fitters.py
