name: Second-Workflow

on:
  workflow_run:
    workflows: ["First-Workflow"]
    types:
      - completed

jobs:

  test-wheel:
    runs-on: ubuntu-latest

    steps:

    - name: respond to greeting
      run: echo "Hello Mars!"
