name: Download wheel and install

on:
  workflow_run:
    workflows: ["Build-Python-Wheel"]
    types:
      - completed

jobs:

  test-wheel:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Download wheel
      uses: actions/download-artifact@v3
      with:
        name: wheel
        path: dist

    - name: Install wheel for configurations other than Windows
      run: python -m pip install dist/bumps-*-py3-none-any.whl
