name: Build the Python wheel and upload as artifact


on: [push, pull_request, workflow_dispatch]

jobs:

  build-wheel:
    runs-on: ubuntu-latest

    steps:

    - name: Fail the workflow
      run: exit 1

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[dev]

    - name: Create wheel
      run: python -m build --wheel --no-isolation

    - name: Upload wheel artifact
      uses: actions/upload-artifact@v3
      with:
        name: wheel
        path: dist/bumps-*-py3-none-any.whl
